### ISSUE TITLE
Discuss: Listing users as admin

### ISSUE THREAD

**Issue by oponder** [giantswarm/api-spec#26]
For a while now I have wanted to be able to easily list all users, along with all their properties. So we can for example tell quickly whether or not they are expired.

I imagine it would live at:

`GET /v4/users/`

Do you think it is ok to have such an endpoint?

ping @marians

**Comment by marians** [comment]
Yes, I think we should have the endpoint `GET /v4/users/`.

In general, I recommend to spec this so that the returned list items aren't complete, but sparse representations of the actual objects. This is how we do it with clusters as well. This means: we select which attribute of the member object are present in the list item. (And BTW adding an attribute later is never a breaking API change.)

**Comment by xh3b4sd** [comment]
I am wondering why we need this now. Why don't we work on the user management story to improve how we actually do user management? There have been rumours we are going to play with dex and stuff. I see that we here now do changes towards our old userd, which I really do not want to do, because we will hopefully throw it away in the upcoming months.

**Comment by oponder** [comment]
> Dex is NOT a user-management system, but acts as a portal to other identity providers through "connectors." 

We still need some place where we keep track of who is supposed to have access to our system, what orgs they belong to, etc. Dex just helps us identify them using something other than a password.

**Comment by oponder** [comment]
And another point: I just don't want to have to ssh into machines and dig into etcd to do user management. This is just something that I think is a basic need for administrators. Even when we swap out userd with something else. 

I want this endpoint regardless of the underlying microservice or storage that we use.

So this technically is part of the user management story.

**Comment by xh3b4sd** [comment]
This sounds like we have to stick with userd, which makes me super sad.

**Comment by oponder** [comment]
We don't have to. I still have to see how far dex helps us. I think dex can replace userd, but not companyd.

**Comment by oponder** [comment]
Done!
